services:
  - type: web
    name: event-management-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://backend-rxua.onrender.com
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://event-management-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: main 